cmake_minimum_required(VERSION 3.13.0)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/lib)
find_package(PkgConfig REQUIRED)
if(${PKG_CONFIG_FOUND})
    execute_process(COMMAND cp ${CMAKE_CURRENT_SOURCE_DIR}/getEnviroment.sh  ./
    )
    execute_process(
    COMMAND bash getEnviroment.sh 
    RESULT_VARIABLE MY_RESULT
    OUTPUT_VARIABLE MY_OUTPUT
    )

    #message("Result of the command: ${MY_RESULT}")
    #message("Output of the command: ${MY_OUTPUT}")
    #message("MY_OUTPUT: ${MY_OUTPUT}")
    set(ENV{PKG_CONFIG_PATH} ${MY_OUTPUT})
    #message("PKG_CONFIG_PATH: $ENV{PKG_CONFIG_PATH}")

    pkg_check_modules( jemalloc REQUIRED jemalloc)
    pkg_check_modules( ace REQUIRED ACE)
    pkg_check_modules( gtest REQUIRED gtest)
    pkg_check_modules( curl REQUIRED libcurl)
    pkg_check_modules( xerces-c REQUIRED xerces-c)
    #pkg_check_modules( uci REQUIRED uci)
    #pkg_check_modules( ubox REQUIRED ubox)
    pkg_check_modules( cjson REQUIRED libcjson)
    #pkg_check_modules( boost REQUIRED libboost_date_time libboost_regex)
    pkg_check_modules( libpcap REQUIRED libpcap)
    pkg_check_modules( libevent REQUIRED libevent)
    pkg_check_modules( gmp REQUIRED gmp)
    pkg_check_modules( protocol REQUIRED protobuf)
    pkg_check_modules( flatbuffers REQUIRED flatbuffers)
    pkg_check_modules( arrow REQUIRED arrow)

    #message("ace_FOUND: ${ace_FOUND}")
    #message("ace_LIBRARIES: ${ace_LIBRARIES}")
    #message("ace_LIBRARIES: ${ace_PRIVATE_LIBRARIES}")
    #message("ace_STATIC_LIBRARIES: ${ace_STATIC_LIBRARIES}")
    #message("ace_LDFLAGS: ${ace_LDFLAGS}")
    #message("ace_CFLAGS: ${ace_CFLAGS}")
    #message("ace_INCLUDE_DIRS: ${ace_INCLUDE_DIRS}")
    #message("ace_LIBRARY_DIRS: ${ace_LIBRARY_DIRS}")
    #message("ace_VERSION: ${ace_VERSION}")

    project(mainlitealigndata)
    add_subdirectory(testcase)
    add_subdirectory(tools)
    add_subdirectory(src)
    add_subdirectory(src/sub/shuffle)
    add_dependencies(litealigndata Shuffle)
    add_dependencies(casemain litealigndata)
    #add_dependencies(apimain casemain)
endif()
install(TARGETS litealigndata DESTINATION .)
install(DIRECTORY seedfile/Ctrldata seedfile/Example DESTINATION .)
